Test subclass: #DRationalTest.
DRationalTest comment: 'Test suite for class DRational, dimensioned rationals.'.

DRationalTest extend
[
    testCreation [
        'Testing creation methods...' displayNl.
    ]

    testAddition [
        'Testing dimensioned rational addition...' displayNl.
    ]

    testSubtraction [
        'Testing dimensioned rational subtraction...' displayNl.
    ]

    testMultiplication [
        'Testing dimensioned rational multiplication...' displayNl.
    ]

    testDivision [
        'Testing dimensioned rational division...' displayNl.
    ]
]
