package lite.scanner;
//----------------------------------------------------
// The following code was generated by CUP v0.9e
// Fri Sep 12 14:15:48 CDT 1997
//----------------------------------------------------

/** Cup generated class containing symbol constants. */
public class SymbolTypes
{
    /* terminals */
    static final int ASG = 6;
    static final int CAND = 15;
    static final int CHARLIT = 9;
    static final int COLON = 52;
    static final int COMMA = 3;
    static final int COR = 16;
    static final int EOF = 0;
    static final int EQ = 19;
    static final int GEQ = 22;
    static final int GT = 18;
    static final int IDENTIFIER = 10;
    static final int INTLIT = 7;
    static final int LBRACE = 11;
    static final int LBRACKET = 13;
    static final int LEQ = 21;
    static final int LPAREN = 4;
    static final int LT = 17;
    static final int MINUS = 24;
    static final int NOT = 27;
    static final int NOTEQ = 20;
    static final int PLUS = 23;
    static final int RBRACE = 12;
    static final int RBRACKET = 14;
    static final int RPAREN = 5;
    static final int SEMI = 2;
    static final int SLASH = 26;
    static final int STRLIT = 8;
    static final int TIMES = 25;
    static final int error = 1;
    static final int rw_BOOL = 36;
    static final int rw_BREAK = 50;
    static final int rw_CHAR = 35;
    static final int rw_CLASS = 28;
    static final int rw_CONST = 29;
    static final int rw_CONTINUE = 51;
    static final int rw_ELSE = 32;
    static final int rw_FALSE = 40;
    static final int rw_IF = 30;
    static final int rw_INT = 34;
    static final int rw_PRINT = 101;
    static final int rw_READ = 33;
    static final int rw_RETURN = 38;
    static final int rw_TRUE = 39;
    static final int rw_VOID = 100;
    static final int rw_WHILE = 31;
    static final int rw_WRITE = 37;
} // SymbolTypes

