
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Mar 05 19:12:31 EST 2013
//----------------------------------------------------

package p3.parse;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int CHAR_LIT = 3;
  public static final int DIVIDE = 6;
  public static final int RIGHT_PAREN = 41;
  public static final int RIGHT_BRACKET = 40;
  public static final int K_BOOL = 12;
  public static final int GE = 8;
  public static final int EQUALS = 7;
  public static final int K_FALSE = 19;
  public static final int K_PRINT = 22;
  public static final int K_CONTINUE = 17;
  public static final int K_IF = 20;
  public static final int K_TRUE = 25;
  public static final int MINUS = 36;
  public static final int SEMICOLON = 42;
  public static final int K_CONST = 16;
  public static final int LT = 32;
  public static final int K_VOID = 26;
  public static final int COMMA = 5;
  public static final int LEFT_BRACE = 28;
  public static final int PLUS = 38;
  public static final int K_ELSE = 18;
  public static final int ASSIGN = 2;
  public static final int K_READ = 23;
  public static final int LE = 31;
  public static final int EOF = 0;
  public static final int LOGICAL_OR = 35;
  public static final int error = 1;
  public static final int RIGHT_BRACE = 39;
  public static final int K_CLASS = 15;
  public static final int LOGICAL_NEGATION = 34;
  public static final int K_RETURN = 24;
  public static final int TIMES = 44;
  public static final int K_INT = 21;
  public static final int COLON = 4;
  public static final int LOGICAL_AND = 33;
  public static final int K_CHAR = 14;
  public static final int NE = 37;
  public static final int K_BREAK = 13;
  public static final int LEFT_PAREN = 30;
  public static final int STRING_LIT = 43;
  public static final int INT_LIT = 11;
  public static final int GT = 9;
  public static final int LEFT_BRACKET = 29;
  public static final int K_WHILE = 27;
  public static final int IDENTIFIER = 10;
}

